import { defineField, defineType } from "sanity";
import { ClipboardList } from "lucide-react";

export default defineType({
  name: "workItem",
  type: "document",
  title: "Task",
  icon: ClipboardList,
  groups: [
    { name: "content", title: "Content" },
    { name: "assignment", title: "Assignment" },
    { name: "links", title: "Links" },
    { name: "collaboration", title: "Collaboration" },
    { name: "status", title: "Status" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "description",
      type: "text",
      title: "Description",
      group: "content",
    }),
    defineField({
      name: "visibility",
      title: "Visibility",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Internal", value: "internal" },
          { title: "Client Visible", value: "client" },
        ],
        layout: "radio",
      },
      initialValue: "internal",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "isTemplate",
      title: "Is Template",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "defaultDueOffset",
      title: "Default Due Offset (Days)",
      description: "For templates: how many days from creation is this due?",
      type: "number",
      group: "content",
      hidden: ({ parent }) => !parent?.isTemplate,
    }),
    defineField({
      name: "checklist",
      title: "Checklist",
      type: "array",
      group: "content",
      of: [
        {
          type: "object",
          fields: [
            { name: "item", type: "string", title: "Item" },
            { name: "completed", type: "boolean", title: "Completed", initialValue: false },
          ],
        },
      ],
    }),
    defineField({
      name: "attachments",
      title: "Attachments",
      type: "array",
      group: "collaboration",
      of: [{ type: "file" }],
    }),
    defineField({
      name: "assignedTo",
      type: "reference",
      title: "Assigned To",
      to: [{ type: "account" }],
      group: "assignment",
    }),
    defineField({
      name: "createdBy",
      type: "reference",
      title: "Created By",
      to: [{ type: "account" }],
      group: "assignment",
      readOnly: true,
    }),
    defineField({
      name: "dueDate",
      type: "datetime",
      title: "Due Date",
      group: "assignment",
    }),
    defineField({
      name: "clientAccount",
      title: "Client Account",
      type: "reference",
      to: [{ type: "account" }],
      options: {
        filter: 'role == "client"',
      },
      group: "links",
    }),
    defineField({
      name: "relatedCampaign",
      title: "Related Campaign",
      type: "reference",
      to: [{ type: "campaign" }],
      group: "links",
    }),
    defineField({
      name: "relatedDeliverable",
      title: "Related Deliverable",
      type: "reference",
      to: [{ type: "deliverable" }],
      group: "links",
    }),
    defineField({
      name: "blockedReason",
      title: "Blocked Reason",
      type: "text",
      group: "collaboration",
    }),
    defineField({
      name: "reassignmentRequestedAt",
      title: "Reassignment Requested At",
      type: "datetime",
      group: "collaboration",
      readOnly: true,
    }),
    defineField({
      name: "reassignmentNote",
      title: "Reassignment Note",
      type: "text",
      group: "collaboration",
    }),
    defineField({
      name: "comments",
      title: "Comments",
      type: "array",
      group: "collaboration",
      of: [
        {
          type: "object",
          name: "workItemComment",
          fields: [
            defineField({
              name: "author",
              title: "Author",
              type: "reference",
              to: [{ type: "account" }],
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: "message",
              title: "Message",
              type: "text",
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: "createdAt",
              title: "Created At",
              type: "datetime",
              initialValue: () => new Date().toISOString(),
              readOnly: true,
              validation: (Rule) => Rule.required(),
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "priority",
      title: "Priority",
      type: "string",
      group: "status",
      options: {
        list: [
          { title: "Low", value: "low" },
          { title: "Medium", value: "medium" },
          { title: "High", value: "high" },
        ],
        layout: "radio",
      },
      initialValue: "medium",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "status",
      options: {
        list: [
          { title: "To Do", value: "todo" },
          { title: "In Progress", value: "in_progress" },
          { title: "Blocked", value: "blocked" },
          { title: "Done", value: "done" },
        ],
        layout: "radio",
      },
      initialValue: "todo",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "createdAt",
      title: "Created At",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
      readOnly: true,
      group: "status",
    }),
  ],
});
